config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :exhibits
  root 'welcome#index'

  mount RailsAdmin::Engine => '/admin', as: :rails_admin
  devise_for :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end 
  end
end

app/models/book_status.rb
class BookStatus < ActiveRecord::Base
  belongs_to :exhibit
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :faculty
end

app/models/exhibit.rb
class Exhibit < ActiveRecord::Base
  belongs_to :user
  belongs_to :exhibit_category
  belongs_to :book_status
  belongs_to :exhibit_status

  mount_uploader :image, ImageUploader

  validates :user_id, presence: true
  validates :exhibit_category_id, presence: true
  validates :image, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validates :exhibit_description, presence: true, length: { maximum: 1000 }
  validates :price, presence: true
  validates :book_status_id, presence: true
  validates :exhibit_status_id, presence: true
end

app/models/exhibit_category.rb
class ExhibitCategory < ActiveRecord::Base
  has_many :exhibits
end

app/models/exhibit_status.rb
class ExhibitStatus < ActiveRecord::Base
  has_many :exhibits
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  has_many :departments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :exhibits
  belongs_to :faculty
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters


    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :student_number
    devise_parameter_sanitizer.for(:account_update) << :admission_year
    devise_parameter_sanitizer.for(:account_update) << :student_number
    devise_parameter_sanitizer.for(:account_update) << :self_introduction
    devise_parameter_sanitizer.for(:account_update) << :faculty_id
    devise_parameter_sanitizer.for(:account_update) << :avatar
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :student_number
    devise_parameter_sanitizer.for(:sign_up) << :admission_year
    devise_parameter_sanitizer.for(:sign_up) << :student_number
    devise_parameter_sanitizer.for(:sign_up) << :self_introduction
    devise_parameter_sanitizer.for(:sign_up) << :faculty_id
    devise_parameter_sanitizer.for(:sign_up) << :avatar

    # devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    # devise_parameter_sanitizer.permit(:account_update, keys: [:student_number])
    # devise_parameter_sanitizer.permit(:account_update, keys: [:admission_year])
    # devise_parameter_sanitizer.permit(:account_update, keys: [:self_introduction])
    # devise_parameter_sanitizer.permit(:account_update, keys: [:faculty_id])
    # devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/exhibits_controller.rb
class ExhibitsController < ApplicationController
  # ログイン済みのユーザのみアクセス可能とするアクション
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # @exhibit = Exhibit.find(params[:id])が必要なアクション
  before_action :set_exhibit, only: [:show, :edit, :update, :destroy]

  # 商品一覧アクション
  def index
    @q = Exhibit.order(created_at: :desc).ransack(params[:q])
    @exhibits = @q.result.page(params[:page]).per(2)
  end

  # 商品新規登録newアクション
  def new
    @exhibit = Exhibit.new
    render layout: 'non_header'
  end

  # 商品新規登録createアクション
  def create
    @exhibit = Exhibit.new(exhibit_params)
    if @exhibit.save
      redirect_to exhibits_url
    else
      render 'new', layout: 'non_header'
    end
  end

  # 商品編集editアクション
  def edit
    render layout: 'non_header'
  end

  # 商品編集updateアクション
  def update
    @exhibit.update(exhibit_params)
    redirect_to @exhibit
  end

  # 商品詳細showアクション
  def show
  end

  # 商品削除destroyアクション
  def destroy
    @exhibit.destroy
    redirect_to exhibits_url, notice: '出品を削除しました'
  end

  private

  # exhibitストロングパラメータ
  def exhibit_params
    params.require(:exhibit).permit(:user_id, :image, :image_cache, :title, :exhibit_description, :exhibit_category_id,:price, :book_status_id, :exhibit_status_id)
  end

  # 共通アクション set_exhibit
  def set_exhibit
    @exhibit = Exhibit.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    messages = resource.errors.full_messages.each do |errmsg|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{errmsg}
      </div>
      EOF
    end
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/exhibits/_form.html.erb
<%= form_for @exhibit do |f| %>

<div class="exhibit-single-container-main-child">
  <div class="form-group">
    <%=f.label :image,"出品画像", class: 'exhibit-label' %> <span class="label label-danger exhibit-danger-label">必須</span>
    <%= f.file_field :image %>
    <%# f.hidden_field :image_cache %>
  </div>
</div>

<div class="exhibit-single-container-main-child">
  <div class="form-group">
    <%= f.label "商品名" %>  <span class="label label-danger exhibit-danger-label">必須</span>
    <%= f.text_field :title, class: "form-control input-lg", :placeholder => "商品名（必須, 30文字まで）" %>
  </div>
  <div class="form-group">
    <%= f.label "商品説明" %>  <span class="label label-danger exhibit-danger-label">必須</span>
    <%= f.text_area :exhibit_description, size: "20x10",class: "form-control input-lg", :placeholder => "商品説明（必須, 1000文字まで）（商品を使用した授業名, 商品の状態, 定価, 注意点など…）"  %>
  </div>
</div>

<div class="exhibit-single-container-main-child">
  <div class="row exhibit-single-container-main-child-col">
    <div class="col-sm-3 exhibit-single-container-main-child-col">
      <h2>商品詳細</h2>
    </div>
    <div class="col-sm-9 exhibit-single-container-main-child-col main-child-col-right">
      <div class="form-group">
        <%= f.label "出品カテゴリー" %>  <span class="label label-danger exhibit-danger-label">必須</span>
        <%= f.collection_select :exhibit_category_id, ExhibitCategory.all, :id, :category_name , { include_blank: " -- " },  { class: "form-control input-lg" } %>
      </div>
      <div class="form-group">
        <%= f.label "商品状態" %>  <span class="label label-danger exhibit-danger-label">必須</span>
        <%= f.collection_select :book_status_id, BookStatus.all, :id, :status_title , { include_blank: " -- " },  { class: "form-control input-lg" } %>
      </div>
    </div>
  </div>
</div>

<div class="exhibit-single-container-main-child exhibit-border-none">
  <div class="row exhibit-single-container-main-child-col">
    <div class="col-sm-3 exhibit-single-container-main-child-col">
      <h2>出品価格</h2>
    </div>
    <div class="col-sm-9 exhibit-single-container-main-child-col">
      <div class="form-group">
        <div class="row">
          <div class="col-sm-2 exhibit-single-container-main-child-col main-child-col-right">
            <%= f.label "価格" %> <span class="label label-danger exhibit-danger-label">必須</span>
          </div>
          <div class="col-sm-1 exhibit-single-container-main-child-col main-child-col-right">
            <span class="yen">¥</span>
          </div>
          <div class="col-sm-9 exhibit-single-container-main-child-col main-child-col-right">
            <%= f.number_field :price, class: "form-control input-lg" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="exhibit-single-container-main-child exhibit-submit">
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :exhibit_status_id, value: 1 %>
  <%= button_tag :type => "submit", :class =>"btn btn-default submit-btn center-block" do %>
  出品する
  <% end %>
</div>

<% end %>

app/views/exhibits/_form_old.html.erb
<%= form_for @exhibit do |f| %>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">
      商品の画像を登録
    </h3>
  </div>
  <div class="panel-body">
    <div class="form-group">
      <%=f.label :image,"商品画像" %>
      <%= f.file_field :image %>
      <%# f.hidden_field :image_cache %>
    </div>
  </div>
</div>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">
      商品の情報を入力
    </h3>
  </div>
  <div class="panel-body">
    <div class="form-group">
      <%= f.label "商品名" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "商品説明" %>
      <%= f.text_area :exhibit_description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "出品カテゴリー" %>
      <%= f.collection_select :exhibit_category_id, ExhibitCategory.all, :id, :category_name , { include_blank: "カテゴリを選択してください" },  { class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= f.label "商品状態" %>
      <%= f.collection_select :book_status_id, BookStatus.all, :id, :status_title , { include_blank: "本の状態を選択してください" },  { class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= f.label "出品価格" %>
      <%= f.number_field :price, class: "form-control" %>
    </div>
  </div>
</div>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.hidden_field :exhibit_status_id, value: 1 %>
<%= button_tag :type => "submit", :class =>"btn btn-default primary-pink btn-lg btn-block" do %>
<span class="glyphicon glyphicon-upload"></span> 出品する
<% end %>
<% end %>

app/views/exhibits/edit.html.erb
<div class="container exhibit-new-container">
  <div class="row">
    <div class="col-sm-12">
      <section class="exhibit-new-top">
        <%= image_tag 'unima-logo', :class => 'exhibit-new-top-logo' %>
      </section>

      <% if @exhibit.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= @exhibit.errors.count %> 件のエラーがあります。</h2>
        <ul>
          <% @exhibit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <section class="exhibit-single-container">
        <div class="exhibit-single-container-title">
          <h1>出品情報を編集</h1>
        </div>
        <div class="exhibit-single-container-main">
          <%= render partial: 'form' %>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/exhibits/index.html.erb
<div class="container">

  <div class="row breadcrumb-row">
    <ul class="breadcrumb">
      <li><a href="#">TOP<br></a></li>
      <li><a href="#">出品一覧</a></li>
    </ul>
  </div>

  <div class="row">
    <!-- 左側 -->
    <div class="col-md-3">

      <section class="left-side-menu search-sec">
        <%= search_form_for @q do |f| %>
        <div class="form-group">
          <%= f.search_field :title_or_exhibit_description_cont, placeholder: "タイトルか説明文を検索", class: "form-control search-btn" %>
          <%= f.submit "検索", style: "display: none" %>
        </div>
        <% end %>
      </section>

      <section class="left-side-menu search-result-count-sec">
        <div class="row search-result-count">
          対象出品数<br>
          <span><%= @exhibits.count %></span> 件
        </div>
      </section>

      <div class="left-side-menu-sec">
        <section class="left-side-menu sort-type-sec">
          <div class="row">
            <div>並び替え（未実装）</div>
            <div class="btn-group" style="">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                並び替えの種類
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="#">価格順</a></li>
                <li><a href="#">評価順</a></li>
                <li><a href="#">名前順</a></li>
                <li><a href="#">出品日順</a></li>
              </ul>
            </div>
          </div>
        </section>


        <section class="left-side-menu category-type-sec">
          <div class="row">
            <div>カテゴリーを選択する（未実装）</div>
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                選択
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="#">数学</a></li>
                <li><a href="#">情報/IT</a></li>
                <li><a href="#">看護/医学</a></li>
                <li><a href="#">アプローチ科目</a></li>
              </ul>
            </div>
          </div>
        </section>

        <section class="left-side-menu price-type-sec">
          <div class="row">
            <div>価格帯を選択する（未実装）</div>
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ￥0-￥500<span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="#">￥3,001~</a></li>
                <li><a href="#">￥1,501~￥3,000</a></li>
                <li><a href="#">￥501~￥1,500</a></li>
                <li><a href="#">￥0~￥500</a></li>
              </ul>
            </div>
          </div>
        </section>

        <section class="left-side-menu exhibit-status-sec">
          <div class="row">
            <div>商品の状態（未実装）</div>
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                傷や汚れあり<span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="#">新品/未開封</a></li>
                <li><a href="#">美品</a></li>
                <li><a href="#">使用感あり</a></li>
                <li><a href="#">傷や汚れあり</a></li>
              </ul>
            </div>
          </div>
        </section>

        <section class="left-side-menu category-type-sec">
          <div class="row">
            <div>出品者の評価（未実装）</div>
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                レーティングを選択<span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="#">★★★★★</a></li>
                <li><a href="#">★★★★☆</a></li>
                <li><a href="#">★★★☆☆</a></li>
                <li><a href="#">★★☆☆☆</a></li>
                <li><a href="#">★☆☆☆☆</a></li>
              </ul>
            </div>
          </div>
        </section>
      </div>
    </div>


    <!-- 右側 -->
    <div class="col-md-9">
      <div class="row">
        <% @exhibits.each do |exhibit| %>
        <%= link_to(exhibit_path(exhibit), style: "color:#0000ff;text-decoration:none") do %>
        <div class="exhibit-card col-md-4">
          <div class="exhibit-card-top">
            <% if exhibit.image? %>
            <%= image_tag exhibit.image.url %>
            <% else %>
            <img src="http://design-ec.com/d/e_others_50/l_e_others_500.png" >
            <% end %>
          </div>
          <div class="exhibit-card-bottom">
            <%= exhibit.title %></br><b>¥ <%= exhibit.price %></b>
          </div>
        </div>
        <% end %>
        <% end %>
        <%= paginate @exhibits %>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/exhibits/show.html.erb
<div class="container">
  <div class="row breadcrumb-row">
    <ul class="breadcrumb">
      <li><a href="#">TOP<br></a></li>
      <li><a href="#">出品詳細</a></li>
    </ul>
  </div>

  <div class="row">
    <!-- 左側 -->
    <div class="col-md-4">

      <div class="left-side-menu-sec">
        <section class="left-side-menu exhibit-detail-sec">
          <div class="row">
            <div class="exhibit-h2">
              出品詳細情報
            </div>
            <div class="exhibit-detail">
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <td>商品価格：</td>
                    <td><%= @exhibit.price %>円</td>
                  </tr>
                  <tr>
                    <td>商品状態：</td>
                    <td><%= @exhibit.book_status.status_title %></td>
                  </tr>
                  <tr>
                    <td>カテゴリ：</td>
                    <td><%= @exhibit.exhibit_category.category_name %></td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </section>
      </div>

      <div class="left-side-menu-sec left-side-menu-exhibit-user-sec">
        <section class="left-side-menu exhibit-user-sec">
          <div class="row">
            <div class="exhibit-h2">
              出品者情報
            </div>
          </div>
        </section>
        <div class="exhibit-user-thumbnail-sec">
          <figure class="exhibit-user-thumbnail-sec-img">

            <div class="image"><%= image_tag @exhibit.user.avatar.url %></div>
          </figure>
          <div class="exhibit-user-name">
            <% if @exhibit.user.name.present? %>
              <%= @exhibit.user.name %>
            <% else %>
              NO NAME
            <% end %>
          </div>
        </div>
        <section class="left-side-menu exhibit-user-sec">
          <div class="row">
            <div class="exhibit-user-selfintroduction">
              <%= simple_format(h(@exhibit.user.self_introduction)) %>
            </div>
          </div>
        </section>
      </div>


      <% if current_user.present? %>
      <% if @exhibit.user_id == current_user.id %>
      <div class="exhibit-edit-sec">
        <%= link_to edit_exhibit_path(@exhibit),:class =>"btn btn-default purchase-btn center-block" do %>
        出品を編集する
        <% end %>
      </div>
      <% else %>
      <div class="exhibit-purchase-sec">
        <%= button_tag :type => "submit", :class =>"btn btn-default purchase-btn center-block" do %>
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>購入手続きへ
        <% end %>
      </div>
      <% end %>
      <% else %>
      <div class="exhibit-purchase-sec">
        <%= button_tag :type => "submit", :class =>"btn btn-default purchase-btn center-block" do %>
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>購入手続きへ
        <% end %>
      </div>
      <% end %>


    </div>

    <!-- 右側 -->
    <div class="col-md-8">
      <div class="row">
        <section class="exihit-show-main-sec">
          <div class="exhibit-show-child exhibit-show-title">
            <h1><%= @exhibit.title %></h1>
          </div>
          <div class="exhibit-show-image">
            <%= image_tag @exhibit.image.url %>
          </div>
          <div class="exhibit-show-description">
            <div class="exhibit-show-description_title">
              商品説明
            </div>
            <%= simple_format(h(@exhibit.exhibit_description)) %>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/layouts/_header.html.erb
    <!-- Start Navigation -->
    <nav class="navbar navbar-default bootsnav">

      <!-- Start Top Search -->
      <div class="top-search">
        <div class="container">
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-search"></i></span>
            <input type="text" class="form-control" placeholder="Search">
            <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
          </div>
        </div>
      </div>
      <!-- End Top Search -->

      <div class="container">
        <!-- Start Atribute Navigation -->
        <div class="attr-nav">
          <ul>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
                <i class="fa fa-shopping-bag"></i>
                <span class="badge">3</span>
              </a>
              <ul class="dropdown-menu cart-list">
                <li>
                </li>
                <li>
                </li>
                <li>
                </li>
                <li class="total">
                  <span class="pull-right"><strong>Total</strong>: $0.00</span>
                  <a href="#" class="btn btn-default btn-cart">Cart</a>
                </li>
              </ul>
            </li>
            <li class="search"><a href="#"><i class="fa fa-search"></i></a></li>
            <li class="side-menu"><a href="#"><i class="fa fa-bars"></i></a></li>
          </ul>
        </div>
        <!-- End Atribute Navigation -->

        <!-- Start Header Navigation -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
            <i class="fa fa-bars"></i>
          </button>
          <a class="navbar-brand" href="/"><%= image_tag 'unima-logo', :width => '189', :height => '33', :class => 'logo' %></a>
        </div>
        <!-- End Header Navigation -->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-menu">
          <ul class="nav navbar-nav navbar-right" data-in="fadeInDown" data-out="fadeOutUp">
            <li><a href="/exhibits">出品一覧</a></li>
            <li class="dropdown megamenu-fw">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">カテゴリ</a>
              <ul class="dropdown-menu megamenu-content" role="menu">
                <li>
                  <div class="row">
                    <div class="col-menu col-md-3">
                      <h6 class="title">Title Menu One</h6>
                      <div class="content">
                        <ul class="menu-col">
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                        </ul>
                      </div>
                    </div><!-- end col-3 -->
                    <div class="col-menu col-md-3">
                      <h6 class="title">Title Menu Two</h6>
                      <div class="content">
                        <ul class="menu-col">
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                        </ul>
                      </div>
                    </div><!-- end col-3 -->
                    <div class="col-menu col-md-3">
                      <h6 class="title">Title Menu Three</h6>
                      <div class="content">
                        <ul class="menu-col">
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-menu col-md-3">
                      <h6 class="title">Title Menu Four</h6>
                      <div class="content">
                        <ul class="menu-col">
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                          <li><a href="#">Custom Menu</a></li>
                        </ul>
                      </div>
                    </div><!-- end col-3 -->
                  </div><!-- end row -->
                </li>
              </ul>
            </li>
            </li>
            <% if user_signed_in? %>
              <li>
                <%= link_to '出品する', new_exhibit_path, class: "btn btn-default primary-pink" %>
              </li>
              <li>
                <%= link_to '設定変更', edit_user_registration_path, class: "btn btn-default primary-pink" %>
              </li>
              <li>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-default sub-blue" %>
              </li>
            <% else %>
              <li>
                <%= link_to 'ログイン', new_user_session_path, class: "btn btn-default primary-pink" %>
              </li>
              <li>
                <%= link_to '新規会員登録', new_user_registration_path, class: "btn btn-default sub-blue" %>
              </li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>

      <!-- Start Side Menu -->
      <div class="side">
        <a href="#" class="close-side"><i class="fa fa-times"></i></a>
        <div class="widget">
          <h6 class="title">Custom Pages</h6>
          <ul class="link">
            <li><a href="#">About</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Portfolio</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
        <div class="widget">
          <h6 class="title">Additional Links</h6>
          <ul class="link">
            <li><a href="#">Retina Homepage</a></li>
            <li><a href="#">New Page Examples</a></li>
            <li><a href="#">Parallax Sections</a></li>
            <li><a href="#">Shortcode Central</a></li>
            <li><a href="#">Ultimate Font Collection</a></li>
          </ul>
        </div>
      </div>
      <!-- End Side Menu -->
    </nav>
    <!-- End Navigation -->

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>